program  largest_simplex
  ! Main program to test silicon potential subroutines
  implicit real*8 (a-h,o-z)
  logical mask
  parameter(ns=1,np=1,natx_sphere=100,len=(ns+3*np)*natx_sphere, nsimplex=100,nconf=99,nenv=792)
  dimension fpall(len,nenv)
  dimension xcart(nsimplex,nsimplex),distsimplex(0:nsimplex,0:nsimplex)
  dimension mask(nenv),indenv(0:nsimplex),temp(0:nsimplex)
  dimension key(2,nenv)
  allocatable xcartw(:,:),distsimplexw(:,:)

    !reading file "fort.25"
    do ienv=1,nenv
     read(25,*) i,key(1,ienv),key(2,ienv)  !ienv,iat,iconf
     if (i.ne.ienv) stop 'error 25'
    enddo
  
! read in all the atomic fingerprints (generated by FPxtaleval.f90)
! fingerprints are read form "FP.dat"
  call  readfp(len, "FP.dat", nenv,fpall)
! generate simplex with the largest volume

     do j=0,nsimplex
     do i=0,nsimplex
     distsimplex(i,j)=0.d0
     enddo
     enddo

     do j=1,nsimplex
     do i=1,nsimplex
     xcart(i,j)=0.d0
     enddo
     enddo

     do ienv=1,nenv
     mask(ienv)=.true.
     enddo


   !finding the largest distance in the data
   call largest_pair_dist(len, nenv,fpall,iienv,jjenv,distmax)
   write(*,*) 'iiat,iiconf,distmax ',key(1,iienv),key(2,iienv),distmax
   write(*,*) 'jjat,jjconf,distmax ',key(1,jjenv),key(2,jjenv),distmax 
   indenv(0)=iienv
   indenv(1)=jjenv
   mask(iienv)=.false.
   mask(jjenv)=.false.
   xcart(1,1)=distmax
   distsimplex(0,0)=0.d0
   distsimplex(1,1)=0.d0
   distsimplex(0,1)=distmax
   distsimplex(1,0)=distmax

   do msim=2,nsimplex

     dmax=0.d0
     iienv=-1
     do ienv=1,nenv
     if (mask(ienv)) then

       distsimplex(msim,msim)=0.d0
       do isim=0,msim-1
         distsimplex(msim,isim)=fpdf(len,fpall(1,ienv),fpall(1,indenv(isim)))
         distsimplex(isim,msim)=distsimplex(msim,isim)
       enddo

!        write(*,*) 'Distimplex ',iconf
!        do i=0,msim
!        write(*,'(12(1x,e9.2))') (distsimplex(i,j),j=0,msim)
!        enddo

       call add_point_simplex(nsimplex,msim,distsimplex,xcart)
!         write(*,*) 'trial Simplex coordinates ',msim
!         do i=1,msim
!         write(*,'(12(1x,e9.2))') (xcart(i,j),j=1,msim)
!         enddo
       if (xcart(msim,msim).gt.dmax) then
         iienv=ienv
         dmax=xcart(msim,msim)
       endif
     


     endif
     enddo

     if (dmax.lt.1.d-6) then
         nsim=msim-1
         goto 2000
     endif

!  repeat calculation for configuration ii which gives largest volume
     distsimplex(msim,msim)=0.d0
     do isim=0,msim-1
         distsimplex(msim,isim)=fpdf(len,fpall(1,iienv),fpall(1,indenv(isim)))
         distsimplex(isim,msim)=distsimplex(msim,isim)
     enddo

!        write(*,*) 'Distimplex recalculated',ii
!        do i=0,msim
!        write(*,'(12(1x,e9.2))') (distsimplex(i,j),j=0,msim)
!        enddo

     call add_point_simplex(nsimplex,msim,distsimplex,xcart)

     indenv(msim)=iienv
     mask(iienv)=.false.
   
   enddo

   nsim=nsimplex
   write(*,*) 'nsim', nsim
   2000 continue
 
   allocate (xcartw(nsim+1,nsim+1),distsimplexw(0:nsim+1,0:nsim+1))
!
   do j=1,nsim
       do i=1,nsim
         xcartw(i,j)=xcart(i,j)
       enddo
   enddo
   do j=0,nsim
   do i=0,nsim
     distsimplexw(i,j)=distsimplex(i,j)
   enddo
   enddo

   open(188,file='reduced_fingerprint')
   do ienv=1,nenv
!
       distsimplexw(nsim+1,nsim+1)=0.d0
       do isim=0,nsim
         distsimplexw(nsim+1,isim)=fpdf(len,fpall(1,ienv),fpall(1,indenv(isim)))
         distsimplexw(isim,nsim+1)=distsimplexw(nsim+1,isim)
       enddo
!       write(12,'(1000(1x,e24.17))') (distsimplexw(nsim+1,isim),isim=0,nsim)
!!        write(*,*) 'Distimplex ',iconf
!!        do i=0,nsim+1
!!        write(*,'(12(1x,e9.2))') (distsimplex(i,j),j=0,nsim+1)
!!        enddo
!       
! the coordinates of ienv in the simplex
       call add_point_simplex(nsim+1,nsim+1,distsimplexw,xcartw)
       write(188,'(1000(1x,e24.17))') (xcartw(isim,nsim+1),isim=1,nsim) 
   enddo
   close(188)
 
   deallocate(xcartw,distsimplexw)

   !categorize environments with their similarity to the simplex
   open(196,file='classification')
   do ienv=1, nenv
      fpdmin = 10000.d0
      iisim = -1
      do isim=0, nsim
         fpd=fpdf(len,fpall(1,ienv),fpall(1,indenv(isim)))
         if(fpd.lt.fpdmin) then
             fpdmin=fpd
             iisim=isim
         endif
      enddo
     write(196,'(3i7,e24.17)') key(1,ienv), key(2,ienv), iisim, fpdmin
      
   enddo
   close(196)

   write(*,*) 'ind '

     write(*,*) ' Simplex corners: isim,iat,icon'
   open(10,file='configs')
   write(10,*) "#isim, iat, iconf"
   do isim=0,nsim
     write(*,*) isim,key(1,indenv(isim)),key(2,indenv(isim))
     write(10,*) isim,key(1,indenv(isim)),key(2,indenv(isim))
   enddo
   close(10)
     !write(*,*) 'Simplex coordinates ',nsim
     !do i=1,nsim
     !write(*,'(12(1x,e9.2))') (xcart(i,j),j=1,nsim)
     !enddo
   write(*,*) 'Diagonal coordinates ',nsim
   write(*,'(12(1x,e9.2))') (xcart(j,j),j=1,nsim)

   call voldet(nsimplex,nsim,xcart,vol,det)
   write(*,*) 'vol,det ',vol,det


!   do ienv=1,nenv
!     do jenv=1,ienv
!        fpd=fpdf(natx_sphere,ns,np,fpall(1,ienv),fpall(1,jenv))
!        fpd=fpd/distmax
!        nden(ienv,jenv)=npoints*fpd
!        !write(13,*) fpd,key(1,ienv),key(2,ienv),key(1,jenv),key(2,jenv)
!     enddo
!   enddo   
end program 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!S U B R O U T I N E S!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

     function fpdf(n,fp1,fp2)
       implicit real*8 (a-h,o-z)
       dimension fp1(n), fp2(n)

       fpdf = 0.d0
       do i=1, n
          fpdf=fpdf+(fp1(i)-fp2(i))**2
       enddo
       fpdf=sqrt(fpdf)
     end function

     subroutine add_point_simplex(nsimplex,nsim,dist,xcart)
     implicit real*8 (a-h,o-z)
     dimension dist(nsimplex+1,nsimplex+1),d2(nsimplex+1,nsimplex+1),xcart(nsimplex,nsimplex)

     if (nsim.le.1) stop 'add_point'

     do j=1,nsimplex+1
     do i=1,nsimplex+1
     d2(i,j)=dist(i,j)**2
     enddo
     enddo

   j=nsim
      do i=1,j-1
        xcart(i,j)=d2(1,j+1) + d2(1,i+1) - d2(i+1,j+1)
          do k=i-1,1,-1
          xcart(i,j)=xcart(i,j)-2.d0*xcart(k,i)*xcart(k,j)
          enddo  
        xcart(i,j)=xcart(i,j)/(2.d0*xcart(i,i))
        !write(*,*) i,j,xcart(i,j)
      enddo
      xcart(j,j)= d2(1,j+1)
      do k=1,j-1   
        xcart(j,j)= xcart(j,j) - xcart(k,j)*xcart(k,j)
      enddo
          xcart(j,j)=sqrt(max(0.d0,xcart(j,j)))


     end subroutine add_point_simplex


     subroutine dist2coord(nsimplex,dist,nsim,xcart)
! Generates the coordinates xcart of a nsim-dimensional sinplex (having nsim+1 corners)
! given the nsim*(nsim+1)/2 nonzero distances between the coners stored in the
! symmetrix matrix dist (whose diagoban is zero). The first index of xcart denotes the cartesian 
! coordiantes of the corners and the second index is counting the corners. 
! The counting of the corners starts with 0 and the 0-th corner is by definition the origin and therefore not stored.
! So the second  index of the array xcart starts with 1
     implicit real*8 (a-h,o-z)
     dimension dist(nsimplex+1,nsimplex+1),d2(nsimplex+1,nsimplex+1),xcart(nsimplex,nsimplex)

     do j=1,nsimplex+1
     do i=1,nsimplex+1
     d2(i,j)=dist(i,j)**2
     enddo
     enddo

     do j=1,nsimplex
     do i=1,nsimplex
     xcart(i,j)=0.d0
     enddo
     enddo


   xcart(1,1)= sqrt(d2(1,2))
   !write(*,*) 1,1,xcart(1,1)
   do j=2,nsimplex
      do i=1,j-1
        xcart(i,j)=d2(1,j+1) + d2(1,i+1) - d2(i+1,j+1)
          do k=i-1,1,-1
          xcart(i,j)=xcart(i,j)-2.d0*xcart(k,i)*xcart(k,j)
          enddo  
        xcart(i,j)=xcart(i,j)/(2.d0*xcart(i,i))
        !write(*,*) i,j,xcart(i,j)
      enddo
      xcart(j,j)= d2(1,j+1)
      do k=1,j-1   
        xcart(j,j)= xcart(j,j) - xcart(k,j)*xcart(k,j)
      enddo
      if (xcart(j,j) .gt. 1.d-12) then 
          xcart(j,j)=sqrt(xcart(j,j))  
          write(*,*) 'diag ',j,xcart(j,j)
      else
          nsim=j-1
          xcart(j,j)=0.d0
          goto 1000
      endif
   enddo

   nsim=nsimplex
   1000 continue

   end subroutine dist2coord


   subroutine largest_pair_dist(len,nenv,fpall,iienv,jjenv,distmax)
!  Find points with the largest distances
   implicit real*8 (a-h,o-z)
   dimension fpall(len,nenv)

   distmax=0.d0
   ic=0
   do ienv=1,nenv
   ic=ic+1
   jc=0
   do jenv=1,nenv
   jc=jc+1
   if (jc.lt.ic)  then

   fpd=fpdf(len, fpall(1,ienv),fpall(1,jenv))
   if (fpd.gt.distmax) then
       distmax=fpd
       iienv=ienv
       jjenv=jenv
!       ii=ic
!       jj=jc
    endif

   endif
   enddo
   enddo

   end subroutine largest_pair_dist




   subroutine voldet(nsimplex,nsim,xcart,vol,det)
   ! Calculate determinant and volume of simplex given in cartesian coordinates
     implicit real*8 (a-h,o-z)
     dimension xcart(nsimplex,nsimplex)
     det=xcart(1,1)
     vol=xcart(1,1)
     do i=2,nsim
     det=det*xcart(i,i)
     vol=vol*xcart(i,i)/i
   enddo
   end subroutine voldet
    


!!program  test
!!     implicit real*8 (a-h,o-z)
!!     parameter(n=20)
!!     dimension dist(n,n),xcart(n-1,0:n-1),xcartin(n-1,0:n-1)
!!
!!
!!     do j=0,n-1
!!     do i=1,n-1
!!     xcartin(i,j)=0.d0
!!     enddo
!!     enddo
!!
!!     call random_number(tt)
!!     call random_number(tt)
!!     do j=1,n-1
!!     do i=1,j
!!     call random_number(tt)
!!     xcartin(i,j)=tt
!!     enddo
!!     enddo
!!
!!     write(*,*) ' XCART IN '
!!     do i=1,n-1
!!     write(*,'(10(1x,e10.3))') (xcartin(i,j),j=0,n-1)
!!     enddo
!!
!!     do j=0,n-1
!!     do i=0,n-1
!!     d=0.d0
!!     do l=1,n-1
!!     d=d+(xcartin(l,i)-xcartin(l,j))**2
!!     enddo
!!     dist(i+1,j+1)=sqrt(d)
!!     enddo
!!     enddo
!!
!!     write(*,*) 'DIST '
!!     do i=1,n
!!     write(*,'(10(1x,e10.3))') (dist(i,j),j=1,n)
!!     enddo
!!
!!     call dist2coord(n,dist,xcart,det,vol)
!!     write(*,*) ' det ,vol ',det,vol
!!
!!     write(*,*) ' XCART OUT '
!!     errmax=0.d0
!!     do i=1,n-1
!!     write(*,'(10(1x,e10.3))') (xcart(i,j),j=0,n-1)
!!     do j=0,n-1
!!     errmax=max(errmax,abs(xcartin(i,j)-xcart(i,j)))
!!     enddo
!!     enddo
!!
!!     write(*,*) 'ERRMAX ',errmax
!!
!!end program 


  subroutine readfp(len, filename, nenv,fpall)
  implicit real*8 (a-h,o-z)
  dimension fpall(len,nenv)
  character(*) :: filename
  
  open(unit=15,file=trim(filename))
     do j=1,nenv
!        read(15,'(800(1x,e24.17))') (fpall(i,j),i=1,len)
         read(15,*) (fpall(i,j),i=1,len)
!         write(*,'(800(1x,e24.17))') (fpall(i,j),i=1,len)
     enddo
  close(15)

  end subroutine readfp


